### ISSUE TITLE
Atualizar a url da API

### ISSUE THREAD

**Issue by yuyura** [AnimeFlitch/flitch#11]
A API do animes tv mudou de url pra uma nova com a última atualização deles ( `https://appanimeplus.tk/meuanimetv-40.php`) os endpoints ainda são os mesmos mas só dá pra assistir anime na última versão.

**Comment by LaksCastro** [comment]
Sim! Vou tentar atualizar este final de semana. Se tiver interesse, você mesmo pode migrar o projeto para a versão > 2.2.0 do Flutter, para então atualizar a URL base. De qualquer forma, muto obrigado pela issue.
